spring:
  profiles: consv01
  application:
    name: config-server

server:
  port: 7110
  
eureka:
  instance:
    hostname: config.server.a1
    instance-id:  ${eureka.instance.hostname}:${spring.cloud.client.ipAddress}:${server.port}
  client: #当eureka为高可用服务之后，服务提供者、服务消费者的注册也不能再是一个节点上，要同时注册到所有的注册中心之上
    service-url:
      defaultZone:  http://10.156.46.45:7070/eureka/,http://10.156.46.45:7071/eureka/,http://10.156.46.45:7072/eureka/
#      defaultZone:  http://eureka1:7070/eureka/,http://eureka2:7071/eureka/,http://eureka3:7072/eureka/


---
spring:
  profiles: consv02
  application:
    name: config-server

server:
  port: 7111
  
eureka:
  instance:
    hostname: config.server.a2
    instance-id:  ${eureka.instance.hostname}:${spring.cloud.client.ipAddress}:${server.port}
  client: #当eureka为高可用服务之后，服务提供者、服务消费者的注册也不能再是一个节点上，要同时注册到所有的注册中心之上
    service-url:
      defaultZone:  http://eureka1:7070/eureka/,http://eureka2:7071/eureka/,http://eureka3:7072/eureka/
      